# -*- coding: utf-8 -*-
"""Copy of Cryptojacking_CPU_Consumption.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Y7tUSfZoxylji9Ma4CXIqH6BztBpeaL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
files.upload()

benign_data = pd.read_excel('capturedMine.xlsx', sheet_name='Benign Websites')
malicious_data = pd.read_excel('capturedMine.xlsx', sheet_name='Malicious')
safe_data = pd.read_excel('capturedMine.xlsx', sheet_name='SafeWebsite')

benign_data.head()

malicious_data.head()

safe_data.head()

benign_only = benign_data.iloc[:,1:3]
time = benign_data.iloc[:,0]
plt.figure(figsize=(12,8))
plt.plot(time, benign_only.iloc[:,0], 'r')
plt.plot(time, benign_only.iloc[:,1],'g')
plt.xlabel('Time (s)', fontsize=20)
plt.ylabel('CPU Consumption %', fontsize=20)
# plt.title('Benign webistes')
plt.legend(fontsize=20)

malicious_only = malicious_data.iloc[:,1:6]

plt.figure(figsize=(12,8))
for i in range(0, 5):
  plt.plot(time, malicious_only.iloc[:,i])
  plt.xlabel('Time (s)', fontsize=20)
  plt.ylabel('CPU Consumption %', fontsize=20)
# plt.title('Malicious Websites')
plt.legend(fontsize=20)

safe_data_only = safe_data.iloc[:, 1:11]
plt.figure(figsize=(12,8))
for i in range(0, 10):
  plt.plot(time, safe_data_only.iloc[:,i])
  plt.xlabel('Time (s)',fontsize=20)
  plt.ylabel('CPU Consumption %',fontsize=20)
# plt.title('Safe websites')
plt.legend(fontsize=14)

